steps:
# Build and push the Docker images using the commit SHA as the tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-gateway:$SHORT_SHA', './api-gateway']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/api-gateway:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/inventory-service:$SHORT_SHA', './inventory-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/inventory-service:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/notification-service:$SHORT_SHA', './notification-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/notification-service:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/order-service:$SHORT_SHA', './order-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/order-service:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-service:$SHORT_SHA', './user-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/user-service:$SHORT_SHA']

# DevSecOps: Scan the SHA-tagged image for vulnerabilities
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'container'
    - 'images'
    - 'scan'
    - 'gcr.io/$PROJECT_ID/api-gateway:$SHORT_SHA' # Scan the correct tag
    - '--format=json'
    - '--severity=HIGH'

# IMPORTANT: Update Kubernetes manifests with the new image tag
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed -i "s/gcr.io\/$PROJECT_ID\/api-gateway:latest/gcr.io\/$PROJECT_ID\/api-gateway:$SHORT_SHA/g" kubernetes/api-gateway.yaml
    sed -i "s/gcr.io\/$PROJECT_ID\/inventory-service:latest/gcr.io\/$PROJECT_ID\/inventory-service:$SHORT_SHA/g" kubernetes/inventory-service.yaml
    sed -i "s/gcr.io\/$PROJECT_ID\/notification-service:latest/gcr.io\/$PROJECT_ID\/notification-service:$SHORT_SHA/g" kubernetes/notification-service.yaml
    sed -i "s/gcr.io\/$PROJECT_ID\/order-service:latest/gcr.io\/$PROJECT_ID\/order-service:$SHORT_SHA/g" kubernetes/order-service.yaml
    sed -i "s/gcr.io\/$PROJECT_ID\/user-service:latest/gcr.io\/$PROJECT_ID\/user-service:$SHORT_SHA/g" kubernetes/user-service.yaml

# Deploy to GKE using the updated manifests
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - 'run'
  - '--filename=kubernetes'
  - '--location=us-central1-a'
  - '--cluster=shopping-website-cluster'
  options:
    logging: CLOUD_LOGGING_ONLY